//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DCEntities : DbContext
    {
        public DCEntities()
            : base("name=DCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cms_groups> cms_groups { get; set; }
        public virtual DbSet<cms_permissions> cms_permissions { get; set; }
        public virtual DbSet<cms_policies> cms_policies { get; set; }
        public virtual DbSet<cms_user> cms_user { get; set; }
        public virtual DbSet<SearchList> SearchLists { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<WebUser> WebUsers { get; set; }
        public virtual DbSet<WebUsersSearchList> WebUsersSearchLists { get; set; }
        public virtual DbSet<Zone> Zones { get; set; }
    }
}
