//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebUser()
        {
            this.WebUsersSearchLists = new HashSet<WebUsersSearchList>();
        }
    
        public long id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string ipAddress { get; set; }
        public string UserType { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public Nullable<long> MemberId { get; set; }
        public Nullable<int> parentId { get; set; }
    
        public virtual cms_user cms_user { get; set; }
        public virtual Zone Zone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebUsersSearchList> WebUsersSearchLists { get; set; }
    }
}
